// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQJNqAFiHmcrJimw_HCFJiXyVDT5tvfw',
    appId: '1:592916168200:web:096653e158e8d540089bbd',
    messagingSenderId: '592916168200',
    projectId: 'kopi-125c2',
    authDomain: 'kopi-125c2.firebaseapp.com',
    storageBucket: 'kopi-125c2.firebasestorage.app',
    measurementId: 'G-62BDQ2CRVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tKlgRXnvdSklTRPdMg9YButtenxWvw0',
    appId: '1:592916168200:android:5a9c378343d159ed089bbd',
    messagingSenderId: '592916168200',
    projectId: 'kopi-125c2',
    storageBucket: 'kopi-125c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCuAsk5GtjUr_OB8wpgyr97BNrZRShCs',
    appId: '1:592916168200:ios:a50b85137da3b0a0089bbd',
    messagingSenderId: '592916168200',
    projectId: 'kopi-125c2',
    storageBucket: 'kopi-125c2.firebasestorage.app',
    iosBundleId: 'com.example.brewmateCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCuAsk5GtjUr_OB8wpgyr97BNrZRShCs',
    appId: '1:592916168200:ios:a50b85137da3b0a0089bbd',
    messagingSenderId: '592916168200',
    projectId: 'kopi-125c2',
    storageBucket: 'kopi-125c2.firebasestorage.app',
    iosBundleId: 'com.example.brewmateCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjQJNqAFiHmcrJimw_HCFJiXyVDT5tvfw',
    appId: '1:592916168200:web:9e9681395be2782e089bbd',
    messagingSenderId: '592916168200',
    projectId: 'kopi-125c2',
    authDomain: 'kopi-125c2.firebaseapp.com',
    storageBucket: 'kopi-125c2.firebasestorage.app',
    measurementId: 'G-D884H99WQM',
  );
}
